# Generated by Django 5.1.2 on 2024-10-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=150, verbose_name='Телефон')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, unique=True, verbose_name='Номер карты')),
                ('bonus', models.PositiveIntegerField(verbose_name='Количество бонусов')),
                ('expiration_date', models.DateField(verbose_name='Действительна до')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_cards', to='bonus.client')),
            ],
        ),
    ]
